[project]
name = "tune_jax"
version = "0.1.0"
authors = [{ name = "Robert Dyro" }]
dependencies = ["jax", "numpy", "tqdm"]
description = "Microbenchmarking hyperparameter tuning for JAX functions."
readme = "README.md"
license = { file = "LICENSE" }

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
indent-width = 2
line-length = 80