name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read  # to fetch code
  actions: write  # to cancel previous workflows

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint_and_typecheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Set up Python 3.11
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
        with:
          python-version: 3.11
      - run: python -m pip install pre-commit types-protobuf
      - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ env.pythonLocation }}-${{ hashFiles('.pre-commit-config.yaml', 'setup.py') }}
      - run: pre-commit run --show-diff-on-failure --color=always --all-files
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Get uv cache dir
        id: uv-cache
        run: |
          python3 -m pip install -U uv pip
          echo "dir=$(uv cache dir)" >> $GITHUB_OUTPUT
          echo "pyver=$(python3 -V)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        name: uv cache
        with:
          path: ${{ steps.uv-cache.outputs.dir }}
          key: ${{ runner.os }}-uv-py${{ steps.uv-cache.outputs.pyver }}
      - name: Install uv and pytest
        run: |
          uv venv --seed ~/.venv
          source ~/.venv/bin/activate
          uv pip install pytest && pip install pytest
          uv pip install .
      - name: Run tests
        run: |
          source ~/.venv/bin/activate
          pytest tests/*